version: 2.1

description: A sample hello world orb

display:
  home_url: https://github.com/anna-buildalert
  source_url: https://github.com/anna-buildalert/demo

jobs:
  build:
    docker:
      - image: circleci/python:latest #use specific version
    steps:
      - run: echo 'hi'
      