version: 2.1

jobs:
  build:
    parameters:
      octopus-channel:
        type: boolean
        default: true
    docker:
      - image: circleci/node:9.6.1
    steps:
      - checkout
      - run: |
          echo "export NUGET=`ls Client/BuildOutput | grep .nupkg`" >> $BASH_ENV
          echo "export VER=`echo $NUGET | cut -d. -f 2-5`" >> $BASH_ENV
          cat $BASH_ENV
      - run: echo $NUGET
      - when:
          condition: << parameters.octopus-channel >>
          steps:
            - run: |
                echo $NUGET
                echo $VER
                cat $BASH_ENV

workflows:
  build:
    jobs:
      - build