version: 2.1



jobs:
  build:
    parameters:
      test:
        type: env_var_name
        default: SLACK_MONITOR_CIRCLE_PROJECT_REPONAME
    docker:
      - image: circleci/node:9.6.1
    steps:
      - run: echo << parameters.test >>
      - run: echo ${<< parameters.test >>}