version: 2.1

jobs:
  artifactory_checkout_code:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run:
          command: |
            while true; do
              sleep 1
              netstat -nputw
              echo "======"
            done
          background: true
      - run: sudo apt-get update && sudo apt-get install tcpflow
      - run:
          command: |
            cd ~ && \
              curl -fL https://getcli.jfrog.io | sh
      - run:
          command: |
            ~/jfrog rt config \
              --url https://stash.jfrog.io/artifactory/ \
              --user \
              --apikey \
              --interactive=false
      - run: ~/jfrog rt ping
      - run: |
          sudo groupadd pcap
          sudo usermod -a -G pcap $USER
          sudo chgrp pcap /usr/sbin/tcpdump
          sudo chmod 750 /usr/sbin/tcpdump
          sudo setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump
          sudo tcpflow -p -c port 80

workflows:
  tests:
    jobs:
      - artifactory_checkout_code