# https://circleci.com/blog/building-and-testing-an-asp-net-core-application/
# Currently CircleCI supports a single Windows image: Windows Server 2019 with Visual Studio 2019.

version: 2.1

orbs:
  buildalert: oss-tools/buildalert@0.0.3

workflows:
  monitor:
    jobs:
      - buildalert/monitor-builds:
          context: 'build_alert'
          circle-project-org: 'annapamma'
          circle-project-reponame: 'sandbox'
          circle-token-envvar: 'SLACK_MONITOR_CIRCLE_TOKEN'
          slack-app-url-envvar: 'SLACK_MONITOR_SLACK_APP_URL'
          gh-token-envvar: 'SLACK_MONITOR_GH_TOKEN'
          alert-threshold-seconds: 120
          alert-threshold-max-builds-per-user: 0
          alert-threshold-max-builds: 0
  monitor-siren-test:
    jobs:
      - buildalert/monitor-builds:
          context: 'build_alert'
          circle-project-org: 'annapamma'
          circle-project-reponame: 'sandbox'
          circle-token-envvar: 'SLACK_MONITOR_CIRCLE_TOKEN'
          slack-app-url-envvar: 'SLACK_MONITOR_SLACK_APP_URL'
          gh-token-envvar: 'SLACK_MONITOR_GH_TOKEN'
          alert-threshold-seconds: 120
          alert-threshold-max-builds-per-user: 0
          alert-threshold-max-builds: 0
          siren-test: true
