version: 2.1

parameters:
  build-api:
    type: boolean
    default: false

jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - run: echo 'hi'


workflows:
  build-chron:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
  build-api:
    when: << pipeline.parameters.build-api >>
    jobs:
      - build
