version: 2.1

jobs:
    persist:
        docker:
          - image: alpine:latest
        steps:
          - run: mkdir test && touch test/hello.txt && echo 'hi' >> test/hello.txt
          - persist_to_workspace:
              root: .
              paths:
                - test
    attach:
      docker:
        - image: alpine:latest
      steps:
        - attach_workspace:
            at: .
        - run: ls

workflows:
  test:
    jobs:
      - persist
      - attach:
          requires:
            - persist