version: 2.1

jobs:
  artifactory_checkout_code:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run:
          command: |
            while true; do
              sleep 1
              netstat -nputw
              echo "======"
            done
          background: true
      - run:
          command: |
            cd ~ && \
              curl -fL https://getcli.jfrog.io | sh
      - run:
          command: |
            ~/jfrog rt config \
              --url https://stash.jfrog.io/artifactory/ \
              --user \
              --apikey \
              --interactive=false
      - run: ~/jfrog rt ping
      - run: sudo tcpdump -i any -w /tmp/http.log
      - run: sudo tcpdump -A -r /tmp/http.log | less

workflows:
  tests:
    jobs:
      - artifactory_checkout_code