version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@1.0.1

jobs:
  test:
    executor: sam/default
    steps:
      - run:
          command: >
            curl -fsSL
            "https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh"
            | bash

            /home/linuxbrew/.linuxbrew/bin/brew shellenv >> $BASH_ENV
          name: Install Homebrew (for Linux)
      - run:
          command: |
            brew tap aws/tap
            brew install aws-sam-cli
            brew install aws-sam-cli
            ln -s /home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.1.0.reinstall /home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.1.0
            echo export PATH="/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.1.0/bin:${PATH}" >> $BASH_ENV
            export PATH="/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.1.0/bin:${PATH}"
            sam --version
          name: Install the AWS SAM CLI

workflows:
  tests:
    jobs:
      - test
