version: 2.1

jobs:
  my-test-job:
    machine: true
    steps:
      - run: |
          if [ ${CIRCLE_BRANCH} == 'test-only-pr' ]
            circleci step halt
          fi
workflows:
  tests:
    jobs:
      - my-test-job