version: 2.1

jobs:
  a:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - run:
          command: sudo mkdir /tmp/memory && top -b -n 5 | sudo tee /tmp/memory/top.txt
          background: true
      - store_artifacts:
          path: /tmp/memory
          destination: top.txt

workflows:
  test:
    jobs:
      - a