version: 2.1

jobs:
    build:
        docker:
          - image: circleci/node:9.6.1
        steps:
          - run: bash --version
          - run: touch hi.tar
          - run: |
              for f in *.tar; do
                echo "$f"
              done
