version: 2.1

parameters:
  build:
    type: boolean
    default: true

jobs:
  my-test-job:
    docker:
      - image: circleci/node:10.8
    steps:
      - run: echo "pretend these are tests"

workflows:
  tests:
    jobs:
      - my-test-job