version: 2.1

jobs:
  my-test-job:
    machine: true
    steps:
      - run: |
          mkdir ~/.ssh
          cat \<<EOT >> ~/.ssh/config
          UseRoaming no

          Host jumphost-base*.prod.circleci.com
            User circle

          Host kube-kubectl-us-east-1-*.infra.circleci.com
            User core
            StrictHostkeyChecking no
            ProxyJump jumphost-base.prod.circleci.com

          Host kubectl-cci-*.infra.circleci.com
            User ec2-user
            StrictHostkeyChecking yes
            ProxyJump jumphost-base.prod.circleci.com
          EOT
          cat ~/.ssh/config
      - run:
          name: jumphost test
          command: |
            ssh -f -N -L 9000:graylog-ui.infra.circleci.com:9000 jumphost-base.prod.circleci.com
            netstat -vanp tcp | grep 9000
            curl localhost:9000

workflows:
  tests:
    jobs:
      - my-test-job