version: 2.1

jobs:
  artifactory_checkout_code:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run:
          command: |
            cd ~ && \
              curl -fL https://getcli.jfrog.io | sh
      - run:
          command: |
            ~/jfrog rt config \
              --url https://stash.jfrog.io/artifactory/ \
              --user \
              --apikey \
              --interactive=false
      - run: ~/jfrog rt ping
      - run: ~/jfrog rt dl stash-shared-sbt-releases/org/scala-sbt/sbt/1.3.13/sbt-1.3.13.jar ~/
      - run: ls -al ~/org/scala-sbt/sbt/1.3.13/

workflows:
  tests:
    jobs:
      - artifactory_checkout_code