# https://circleci.com/blog/building-and-testing-an-asp-net-core-application/
# Currently CircleCI supports a single Windows image: Windows Server 2019 with Visual Studio 2019.

version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - run: echo ${GH_TOKEN}

workflows:
    build-with-context:
      jobs:
        - build:
            context: sf-demo