version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.7
    steps:
      - checkout
      - run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade setuptools && pip install wheel
          pip install --upgrade pip
          pip install django-test-plus==1.4.0
