version: 2.1

orbs:
    win: circleci/windows@2.4.0

jobs:
    build:
        executor: win/default
        steps:
            - run:
                name: build environment variable for package name
                command: |
                    [Environment]::SetEnvironmentVariable(
                      'PARENT_BRANCH',
                      "<< pipeline.git.branch >>".Substring(("<< pipeline.git.branch >>".IndexOf('/'))+1),
                      [EnvironmentVariableTarget]::User
                    )
            - run:
                name: echo env
                command: |
                    $env:PARENT_BRANCH
