version: 2.1

jobs:
  a:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - checkout
      - run: echo "a"
  b:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - checkout
      - run: echo "b"

workflows:
  test:
    jobs:
      - a
      - b