version: 2.1

jobs:
  my-test-job:
    docker:
      - image: circleci/ruby:2.6.0-stretch
    steps:
      - checkout
      - run: sudo gem install rspec
      - run: rspec --version
      - run: which rspec


workflows:
  tests:
    jobs:
      - my-test-job