version: 2.1

parameters:
  test:
    type: env_var_name
    default: SLACK_MONITOR_CIRCLE_PROJECT_REPONAME

jobs:
  build:
#    environment:
#      TEST: ${ENVVAR_IN_MY_CONTEXT}
    docker:
      - image: circleci/node:9.6.1
    steps:
      - run: echo << pipeline.parameters.test >>
# "${ENVVAR_IN_MY_CONTEXT}"