version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.8
    steps:
      - run: |
          RESULT=(exit 8)
          echo ${RESULT}

workflows:
  workflow-should-only-trigger-with-api:
    jobs:
      - build
