version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - run: |
          curl -sSL https://sdk.cloud.google.com > /tmp/gcl && bash /tmp/gcl --install-dir=~/gcloud --disable-prompts;
          ~/gcloud/google-cloud-sdk/bin/gcloud components install app-engine-java
      - run: ~/gcloud/google-cloud-sdk/bin/gcloud --help

