version: 2.1 # Use version 2.1 to enable orb usage.

parameters:
  file_id:
    type: string
    default: '25196_20200714232853'

jobs:
  build:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run: python --version
      - run: pip install -r requirements.txt
      - run:
          command: python pa.py << pipeline.parameters.file_id >>
          no_output_timeout: 2h
      - run:
          command: python pa_fail.py << pipeline.parameters.file_id >>
          when: on_fail

workflows:
  run-pa:
    jobs:
      - build

