version: 2.1

jobs:
  my-test-job:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: sbt --version
      - run: echo $PATH
  my-test-job-with-manual-install:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run:
          name: Get sbt binary
          command: sudo apt update && apt install -y curl
      - run: sudo curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
      - run: sudo dpkg -i sbt-$SBT_VERSION.deb
      - run: sudo rm sbt-$SBT_VERSION.deb
      - run: sudo apt-get update
      - run: sudo apt-get install -y python-pip git
      - run: sudo pip install awscli
      - run: sudo apt-get clean && apt-get autoclean
      - run: sbt --version
      - run: echo $PATH

workflows:
  tests:
    jobs:
      - my-test-job
      - my-test-job-with-manual-install