version: 2.1

jobs:
  build:
    parameters:
      octupus-channel:
        type: boolean
        default: true
    docker:
      - image: circleci/node:9.6.1
    steps:
      - when:
          condition: << parameters.octopus-channel >>
          steps:
            - run: echo "hello"

workflows:
  build:
    jobs:
      - build