version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - run: echo 'hi'

workflows:
  ignore-pr-b: # this should not be added as a check to pr-a
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - pr-a