version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - run: |
          curl -sSL https://sdk.cloud.google.com > /tmp/gcl && bash /tmp/gcl --install-dir=~/gcloud --disable-prompts;
          ~/gcloud/google-cloud-sdk/bin/gcloud components install app-engine-java
          echo 'export PATH="/usr/lib/google-cloud-sdk/bin:$PATH"' >> $BASH_ENV
      - run: echo $PATH
