version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: "Check docker"
          command: |
            Invoke-WebRequest -URI https://www.python.org/ftp/python/3.8.1/python-3.8.1-embed-amd64.zip
