version: 2.1

jobs:
  my-test-job:
    docker:
      - image: circleci/ruby:2.6.0-stretch
    steps:
      - checkout
      - run:
          command: cat $BASH_ENV


workflows:
  tests:
    jobs:
      - my-test-job