version: 2.1 # Use version 2.1 to enable orb usage.

parameters:
  file_id:
    type: string
    default: '25196_20200714232853'

jobs:
  build:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run: python --version
      - restore_cache:
          keys:
            - v1-{{ checksum "requirements.txt" }}
            - v1-
      - run: pip install -r requirements.txt
      - run: pip show numpy
      - save_cache:
          key: v1-{{ checksum "requirements.txt" }}
          paths:
            - "/home/circleci/.pyenv/versions/3.7.8/lib/python3.7/site-packages"
      - run:
          command: python pa.py << pipeline.parameters.file_id >>
          no_output_timeout: 2h
      - run:
          command: python pa_fail.py << pipeline.parameters.file_id >>
          when: on_fail

workflows:
  run-pa:
    jobs:
      - build:
          context: context