version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@1.0.1

jobs:
  test:
    executor: sam/default
    steps:
      - run: |
          curl -fsSL "https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh" | bash
          echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >> $BASH_ENV
          eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
      - run: |
          brew tap aws/tap
          brew install aws-sam-cli
          sam --version

workflows:
  tests:
    jobs:
      - test