version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:12.16.2
    steps:
      - run: echo 'hello'

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^config-test.*/

# only: /^config-test.*/
