version: 2.1

jobs:
  my-test-job:
    machine: true
    steps:
      - run: |
          sudo  apt remove curl \
          && sudo apt purge curl \
          && sudo apt-get update \
          && sudo apt-get install -y libssl-dev autoconf libtool make \
          && cd /usr/local/src \
          && sudo rm -rf curl* \
          && sudo wget https://curl.haxx.se/download/curl-7.70.0.zip \
          && sudo unzip curl-7.70.0.zip \
          && cd curl-7.70.0 \
          && sudo ./buildconf \
          && sudo autoreconf --install \
          && sudo ./configure --with-ssl \
          && sudo make \
          && sudo make install \
          && sudo cp /usr/local/bin/curl /usr/bin/curl \
          && cat ./config.sub
workflows:
  tests:
    jobs:
      - my-test-job