version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.8

    steps:
      - run: echo 'test'
      - run: ip -4 -o address
      - setup_remote_docker
      - run: |
          ssh remote-docker
          echo "this echo command will be executed in the remote Docker environment rather than the initial job container itself"
          ip -4 -o address

workflows:
  example-workflow:
    jobs:
      - build