version: 2.1

jobs:
  my-test-job:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: |
          sudo apt-get update
          sudo apt-get install sbt
      - run: echo $FOO

workflows:
  tests:
    jobs:
      - my-test-job