version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: Evaluate Results
          command: |
            grep -q 'failure' /tmp/test-results/test-output
            if [ $? == 0 ]
            then
              echo '-- THE FOLLOWING TESTS FAILED: --'
              exit 1
            else
              echo '-- ALL TESTS PASSED! --'
            fi
