version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - run: echo "hello world"


# follow project
# checkout
# jobs
# workflows: https://circleci.com/gh/annapamma/sandbox/186
# parallelism: https://circleci.com/gh/annapamma/sandbox/189
# resource classes: https://circleci.com/gh/annapamma/sandbox/191
# caching: https://circleci.com/gh/annapamma/sandbox/192
# bonus: reusable config