version: 2.1

orbs:
  diagnostic-orb: circleci/diagnostic-orb@1.0.0

jobs:
  a:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - diagnostic-orb/memory
      - run:
          command: echo 'test'
      - diagnostic-orb/store-report

workflows:
  test:
    jobs:
      - a
