version: 2.1

jobs:
  build:
    parameters:
      octopus-channel:
        type: boolean
        default: true
    docker:
      - image: circleci/node:9.6.1
    steps:
      - checkout
      - run: echo << pipeline.number >>
      - run: echo $NUGET
      - when:
          condition: << parameters.octopus-channel >>
          steps:
            - run: |
                echo $NUGET
                echo $VER
                cat $BASH_ENV

workflows:
  build:
    jobs:
      - build