version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.7
    steps:
      - checkout
      - run: |
          pip install --upgrade setuptools
          pip install --upgrade pip
          pip install django-test-plus==1.4.0

