version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.8

    steps:
      - run: echo "hello world" > test.txt
      - run: checksum test.txt

workflows:
  example-workflow:
    jobs:
      - build