version: 2.1
executors:
  maven-executor:
    docker:
    - {image: 'circleci/openjdk:11-jdk-stretch'}
    working_directory: ~/app

orbs: {slack: circleci/slack@3.4.2}

jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - run: sleep 10000
