version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - run: |
          curl --location --request POST 'https://api.github.com/repos/annapamma/sandbox/issues/4/comments' \
          --header 'Accept: application/vnd.github.comfort-fade-preview+json' \
          --header "Authorization: token ${GH_TOKEN}" \
          --header 'Content-Type: application/json' \
          -d '{
            "body": "Me too2"
          }'

workflows:
   build-then-test:
      jobs:
        - build

