version: 2.1

parameters:
  checking:
    type: boolean
    default: true

jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - run: echo 'hi'


workflows:
  build:
    when: << pipeline.parameters.checking >>
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
