version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/python:3.8'
    steps:
      - run: sudo pip3 install speedtest-cli
      - run: speedtest

workflows:
  test:
    jobs:
      - build