version: 2.1
orbs:
  node: circleci/node@2.1.1
jobs:
  install-node-12:
    docker:
      - image: cimg/node:12.16.2
    steps:
      - checkout
      # - node/install-yarn:
      #     version: 1.22.4
      - run: node --version
      - run: yarn --version
workflows:
  install-n:
    jobs:
      - install-node-12