version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@1.0.1

jobs:
  test:
    executor: sam/default
    steps:
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update && sudo apt-get install build-essential curl file git python3-pip python3
      - run: |
          python3 --version
          pip3 --version
          pip3 install aws-sam-cli
          sam --version

workflows:
  tests:
    jobs:
      - test
