version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@1.8.4

jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - run: echo 'hello world'

workflows:
  install_and_configure_cli:
    jobs:
      - gcp-cli/install_and_initialize_cli:
          executor: gcp-cli/default
      - test