version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
    steps:
      - checkout
      - run: choco install python --version=3.8.0
      - run: python --version