version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3-browsers
    steps:
      - run: sudo rm -rf /var/lib/apt/lists/* && sudo apt update
      - run: sudo apt-get update && sudo apt-get install -y python-pip libpython-dev