version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
  test:
    docker:
      - image: circleci/node:9.6.1
    parallelism: 3
    steps:
      - checkout
      - run: echo 'i am running A LOT OF tests'

workflows:
  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build

# follow project
# checkout
# jobs
# workflows: https://circleci.com/gh/annapamma/sandbox/186
# parallelism: https://circleci.com/gh/annapamma/sandbox/189
# resource classes: https://circleci.com/gh/annapamma/sandbox/191
# caching:
  # before:
  # after:
  # https://circleci.com/gh/annapamma/sandbox/192
# bonus: reusable config