version: 2.1

jobs:
  my-test-job:
    machine: true
    steps:
      - checkout
      - run: |
          COMMIT_SUBJECT=`git log -1 --pretty=%s.`
          IGNORE_BRANCH=$(echo "${COMMIT_SUBJECT}" | sed -En 's/.*\[ignore-branch:(true)\].*/\1/p')
          echo "Commit subject: ${COMMIT_SUBJECT}"
          echo "ignore-branch: ${IGNORE_BRANCH}"
      - run: |
          if [ "$CIRCLE_BRANCH" == 'test-only-pr' ]; then
            circleci step halt
            exit 0
          fi
          echo "$CIRCLE_BRANCH"
          echo "this runs if the halt did not work"
workflows:
  tests:
    jobs:
      - my-test-job