version: 2.1

jobs:
  my-test-job:
    docker:
      - image: circleci/ruby:2.6.0-stretch
    steps:
      - checkout
      - run: |
          echo "Bundle Path:   $BUNDLE_PATH"
          bundle check --path=vendor/bundle || bundle install --path=vendor/bundle && bundle clean
      - run: |
          echo "DEBUGGING:"
          ls -al
          echo "PATH:  $PATH"
          echo "Bundle Path:  $BUNDLE_PATH"
          which bundle
          # rm -rf vendor/bundle
          echo "Running tests"
          bundle exec rspec


workflows:
  tests:
    jobs:
      - my-test-job