version: 2.1

jobs:
  build:
    docker:
      - image: google/cloud-sdk
        environment:
          TERM: xterm
          CI: false
    steps:
      - run: curl -sL https://deb.nodesource.com/setup_10.x | sudo bash - && sudo apt-get install -y nodejs build-essential
