version: 2.1

jobs:
    build:
        docker:
          - image: circleci/node:9.6.1
        steps:
          - run: bash --version
          - run: mkdir 1 && mkdir 1/2 && mkdir 1/2/3
          - run: |
              shopt -s globstar
              for f in 1/**; do
                echo "$f"
              done
