version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - run: |
          curl -sSL https://sdk.cloud.google.com > /tmp/gcl && bash /tmp/gcl --install-dir=~/gcloud --disable-prompts;
          ~/gcloud/google-cloud-sdk/bin/gcloud components install app-engine-java
          echo "alias gcloud='~/gcloud/google-cloud-sdk/bin/gcloud'" >> $BASH_ENV
      - run: alias
      - run: gcloud --version

