version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

  test:
    docker:
      - image: circleci/node:9.6.1
    parallelism: 3
    steps:
      - checkout
      - run: echo 'running A LOT OF tests'

workflows:
   build-then-test:
      jobs:
        - build
        - test:
            requires:
              - build


