version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - checkout
      - run: echo 'hello world!'

# following a project on CircleCI
# jobs: hello world
# workflows: build - then test
# parallel: timing data