version: 2.1

jobs:
  my-test-job:
    docker:
      - image: circleci/ruby:2.6.0-stretch
    steps:
      - checkout
      - run: |
          echo "export FOO='BAR'" >> $BASH_ENV
          cat $BASH_ENV
      - run: echo $FOO

workflows:
  tests:
    jobs:
      - my-test-job