version: 2.1

parameters:
  bar:
    type: string
    default: 'bar'

jobs:
  build:
    docker:
      - image: circleci/node:latest
    environment:
       FOO: << pipeline.parameters.bar >>
    steps:
      - run: echo "(echo ${FOO})"
