version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - run: echo ${CIRCLE_PROJECT_USERNAME}
      - run: echo $foo
      - run: echo ${CIRCLE_BRANCH}

workflows:
    build:
        jobs:
            - test