version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@1.0.1

jobs:
  test:
    executor: sam/default
    steps:
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update && sudo apt-get install build-essential curl file git
      - run:
          name: Install Linuxbrew
          command: |
            sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
            echo 'sudo eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >> $BASH_ENV
            cat $BASH_ENV
      - run: |
          brew tap aws/tap
          brew install aws-sam-cli
          sam --version


workflows:
  tests:
    jobs:
      - test