version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - run: echo "boop" > artifact.txt
      - store_artifacts:
          path: tmp
          destination: artifact.txt