version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - run: echo 'hello'

workflows:
    build_not_master:
        when:
            condition:
                not:
                    - equal: [ master, << pipeline.git.branch >> ]
        jobs:
            - test
    build_master:
        when:
            condition:
                equal: [ master, << pipeline.git.branch >> ]
        jobs:
            - test