version: 2.1

orbs:
  diagnostic-orb: circleci/diagnostic-orb@1.0.0

jobs:
  a:
    environment:
      TERM: xterm
    docker:
      - image: circleci/node:9.6.1
    steps:
      - run:
          command: FILE=~/project/memory-usage-actual.txt; while true; do ps -u ubuntu eo pid,%cpu,%mem,args,uname --sort=-%mem >> $FILE; echo "----------" >> $FILE; sleep 1; done
          background: true

workflows:
  test:
    jobs:
      - a:
          pre-steps:
            - diagnostic-orb/memory
          post-steps:
            - diagnostic-orb/store-report
