version: 2.1

parameters:
  image-test:
    type: string
    default: '8-jdk-stretch'

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:<< pipeline.parameters.image-test >>'
    steps:
      - run: |
          curl -s https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-283.0.0-linux-x86_64.tar.gz | tar xz
          echo 'source ~/google-cloud-sdk/path.bash.inc' >> $BASH_ENV
      - run: gcloud version