version: 2.1

jobs:
  my-test-job:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: sbt --version
      - run: echo $PATH
  my-test-job-with-manual-install:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: sbt --version
      - run: cat /home/circleci/.sbt/boot/update.log
#      - run: mkdir -p /home/circleci/.sbt/boot && echo "test" > /home/circleci/.sbt/boot/update.log
      - store_artifacts:
          path: /home/circleci/.sbt/boot

workflows:
  tests:
    jobs:
      - my-test-job
      - my-test-job-with-manual-install