version: 2.1

parameters:
  bar:
    type: string
    default: 'fshkjsdhks'

jobs:
  build:
    docker:
      - image: foo/bar:latest
    environment:
       FOO: << pipeline.parameters.bar >>
    steps:
      - run: echo ${FOO}
