version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@1.0.1

jobs:
  test:
    executor: sam/default
    steps:
      - run: |
          curl -fsSL "https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh" | bash
          test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
          test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
          test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >> $BASH_ENV
          echo "eval \$($(brew --prefix)/bin/brew shellenv)" >> $BASH_ENV
      - run: |
          brew tap aws/tap
      - run: brew install aws-sam-cli
      - run: sam --version

workflows:
  tests:
    jobs:
      - test