version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - run: sudo curl -sL https://deb.nodesource.com/setup_10.x | bash - && apt-get install -y nodejs build-essential
