version: 2.1

orbs:
  diagnostic-orb: circleci/diagnostic-orb@1.0.0

jobs:
  a:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - run:
          command: sudo mkdir /tmp/memory && top -b | sudo tee /tmp/memory/top.txt
          background: true
      - store_artifacts:
          path: /tmp/memory
          destination: top.txt
      - run: cat /tmp/memory/top.txt

workflows:
  test:
    jobs:
      - a