version: 2.1

jobs:
  my-test-job:
    docker:
      - image: circleci/node:10.8
    steps:
      - run:
          name: jumphost test
          command: |
            ssh -f -N -L 9000:graylog-ui.infra.circleci.com:9000 jumphost-base.prod.circleci.com
            netstat -vanp tcp | grep 9000
            curl localhost:9000

workflows:
  tests:
    jobs:
      - my-test-job