version: 2.1

orbs:
    win: circleci/windows@2.4.0

jobs:
    build:
        executor: win/default
        steps:
            - run:
                name: build environment variable for package name
                command: |
                    $PARENT_BRANCH = "<< pipeline.git.branch >>".Substring(("<< pipeline.git.branch >>".IndexOf('/'))+1)
                    [Environment]::SetEnvironmentVariable('DOCKER_HOST', 'tcp://docker.artofshell.com:2376', [EnvironmentVariableTarget]::User)
                    $env:DOCKER_HOST
