version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - run: curl -sL https://deb.nodesource.com/setup_10.x | sudo bash - && sudo apt-get install -y nodejs build-essential
