version: 2.1

parameters:
  bar:
    type: env_var_name
    default: 'fshkjsdhks'

jobs:
  build:
    docker:
      - image: circleci/node:latest
    environment:
       FOO: << pipeline.parameters.bar >>
    steps:
      - run: echo ${FOO}
