version: 2.1

orbs:
  python: circleci/python@0.3.2

parameters:
  branch:
    type: string
    default: "master"
  mobile:
    type: boolean
    default: true
  desktop:
    type: boolean
    default: true
  tablet:
    type: boolean
    default: true
  tag:
    type: string
    default: ''
  feature:
    type: string
    default: 'all'
  url:
    type: string
    default: 'https://pre-prod.vehiculum.de'

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run: which shovel

workflows:
  main:
    jobs:
      - build
