version: 2.1

orbs:
  diagnostic-orb: circleci/diagnostic-orb@1.0.0

jobs:
  a:
    environment:
      TERM: xterm
    docker:
      - image: circleci/node:9.6.1
    steps:
      - run:
          command: sudo top -b -n 1 > top.txt
      - run: cat top.txt

workflows:
  test:
    jobs:
      - a