version: 2.1

jobs:
  a:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - run: echo 'a'
  b:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - run: echo 'b'
  c:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - run: echo 'c'

workflows:
  test:
    jobs:
      - a
      - b
      - c:
          context: context
          requires:
            - a
            - b
