version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - checkout
      - run: echo "hello world"

# add step to follow project?
# checkout
# hello world
# jobs
# workflows
# parallelism
# resource classes
# caching
# save artifacts