version: 2.1

jobs:
  my-test-job:
    machine: true
    steps:
      - checkout
      - run: |
          COMMIT_SUBJECT=`git log -1 --pretty=%s.`
          IGNORE_BRANCH=$(echo "${COMMIT_SUBJECT}" | sed -En 's/.*\[ignore-branch:(true)\].*/\1/p')
          echo "Commit subject: ${COMMIT_SUBJECT}"
          echo "ignore-branch: ${IGNORE_BRANCH}"
          if [ "IGNORE_BRANCH" == 'true' ]; then
            exit 0
          fi
          echo 'this should not run'
      - run: |
          if [ "$CIRCLE_BRANCH" == 'branch-to-ignore' ]; then
            exit 0
          fi
workflows:
  tests:
    jobs:
      - my-test-job