version: 2.1

parameters:
  image-test:
    type: string
    default: '8-jdk-stretch'

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:<< pipeline.parameters.image-test >>'
    steps:
      - run: echo "hello world"
