version: 2.1

jobs:
  my-test-job:
    machine: true
    steps:
      - run: |
          echo ${CIRCLE_BRANCH}
          circleci step halt
      - run: |
          COMMIT_SUBJECT=`git log -1 --pretty=%s.`
          IGNORE_BRANCH=`echo ${COMMIT_SUBJECT} | sed 's/.*\[ignore-branch:\([^]]*\)\].*/\1/g'`
          echo "Commit subject: ${COMMIT_SUBJECT}"
          echo "username: ${IGNORE_BRANCH}"
workflows:
  tests:
    jobs:
      - my-test-job