version: 2.1

jobs:
  artifactory_checkout_code:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: echo $CIRCLE_WORKING_DIRECTORY/sbt-1.3.13.jar
      - run: echo "$CIRCLE_WORKING_DIRECTORY/sbt-1.3.13.jar"
      - run: echo "${CIRCLE_WORKING_DIRECTORY}/sbt-1.3.13.jar"

workflows:
  tests:
    jobs:
      - artifactory_checkout_code