version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.8
    steps:
      - run: |
          (exit 8 | export RESULT=$?)
          echo ${RESULT}
          echo "test"

workflows:
  workflow-should-only-trigger-with-api:
    jobs:
      - build
