version: 2.1
orbs:
  python: circleci/python@0.2.1

jobs:
  build_and_test:
    executor: python/default
    working_directory: ~/workspace
    #  - image: circleci/python:latest
    #    restart: on-failure # Restart the container if it exits due to an error
    steps:
      - checkout
      - run: pip install -r requirements.txt
#      - python/load-cache
#      - python/install-deps:
#          local: false
#      - python/save-cache
      #- run: pip install -r requirements.txt
      - run: pytest --version
workflows:
  main:
    jobs:
      - build_and_test
