version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - run: |
          echo "test" >> $BASH_ENV
          echo "export FOO='BAR'" >> $BASH_ENV
          ls Client/BuildOutput
          echo "export NUGET='$(ls Client/BuildOutput | grep .nupkg)'" >> $BASH_ENV
          cat $BASH_ENV
      - run: |
          echo $FOO
          echo $NUGET

