version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - add_ssh_keys:
          fingerprints:
            - "18:29:20:fa:30:07:2f:0a:78:9b:0e:de:9f:b6:fd:fe"
      - run: |
          GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_fingerprint'
          git clone git@github.com:annapamma/sandbox.git ~/sandbox

workflows:
  test-ssh:
    jobs:
      - build
