version: 2.1



jobs:
  build:
#    environment:
#      TEST: ${ENVVAR_IN_MY_CONTEXT}
    parameters:
      test:
        type: env_var_name
        default: SLACK_MONITOR_CIRCLE_PROJECT_REPONAME
    docker:
      - image: circleci/node:9.6.1
    steps:
      - run: echo << parameters.test >>
# "${ENVVAR_IN_MY_CONTEXT}"