version: 2.1

jobs:
  my-test-job:
    docker:
      - image: circleci/php:7.2-apache-stretch-node-browsers-legacy
    steps:
      - checkout
      - run: sudo apt-get install libxss1
      - run: sudo aptitude search libXss

workflows:
  tests:
    jobs:
      - my-test-job:
          context: context