version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.8
    steps:
      - run: mkdir -p test/testa && echo "bar" > test/testa/foo.txt
      - persist_to_workspace:
          root: test
          paths:
            - testa
  deploy:
    docker:
      - image: circleci/node:10.8
    steps:
      - attach_workspace:
          at: .

workflows:
  example-workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build

