version: 2.1

orbs:
  diagnostic-orb: circleci/diagnostic-orb@1.0.0

jobs:
  a:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - run: stress --vm 2 --vm-bytes 128M
      - run: top > hello.txt
      - run: cat hello.txt

workflows:
  test:
    jobs:
      - a:
          post-steps:
            - diagnostic-orb/memory
            - diagnostic-orb/store-report
