version: 2.1

jobs:
  my-test-job:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: sbt --version
      - run: echo "somesecret=${HELLO}" > test_file
      - run: cat test_file

workflows:
  tests:
    jobs:
      - my-test-job:
          context: context