version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@1.0.1

jobs:
  test:
    executor: sam/default
    steps:
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get install build-essential python python-setuptools
      - run:
          name: Install Linuxbrew
          command: |
            yes | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)" || true
            export PATH="$HOME/.linuxbrew/bin:$PATH"
            brew tap aws/tap
            brew install aws-sam-cli
            sam --version
      - run: |
          brew tap aws/tap
          brew install aws-sam-cli
          sam --version


workflows:
  tests:
    jobs:
      - test