version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: Evaluate Results
          command: |
            exit 1
      - run:
          name: Echo for failed tests
          command: |
            echo '-- THE FOLLOWING TESTS FAILED: --'
          when: on_success
      - run:
          name: Echo for passed tests
          command: |
            echo '-- THE FOLLOWING TESTS PASSED: --'
          when: on_fail
