version: 2.1

jobs:
  test:
    machine: true
    steps:
      - run: |
          brew tap aws/tap
          brew install aws-sam-cli
          sam --version

workflows:
  tests:
    jobs:
      - test