version: 2.1

jobs:
  build:
    environment:
      TEST: ${SLACK_MONITOR_CIRCLE_PROJECT_REPONAME}
    docker:
      - image: circleci/node:9.6.1
    steps:
     - run: echo 'hello world'
     - run: echo ${TEST}
