version: 2.1

commands:
  provision-k8s:
    parameters:
      customer:
        type: string
        default: mycompany
      environment:
        type: string
        default: prod
    steps:
      - run:
          name: Provision VPC and EKS cluster
          command: |
		    echo << parameters.customer >>-<< parameters.environment >>

jobs:
  prep_k8s:
    docker:
      - image: circleci/node:14.4
    steps:
      - provision-k8s:
          parameters:
		    customer:
			  type: string
			  default: mycompany
		    environment:
			  type: string
			  default: prod

workflows:
  version: 2
  deploy_k8s_workflow:
    jobs:
      - prep_k8s:
          customer: 'BaringsBank'
          environment: 'dev'
