version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - run: echo << pipeline.git.branch >>

workflows:
    do_not_build:
        when:
            condition:
                not:
                  - equal: [ pr-a, << pipeline.git.branch >> ]
        jobs:
            - test
    build:
        when:
            condition:
                equal: [ pr-a, << pipeline.git.branch >> ]
        jobs:
            - test