version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - checkout
      - run: echo 'i am building'
  test:
    docker:
      - image: circleci/node:9.6.1
    parellelism: 3
    steps:
      - checkout
      - run: echo 'i am running A LOT OF tests'

workflows:
  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build

# follow project
# checkout
# hello world
# jobs
# parallelism
# resource classes
# workflows
# caching
