version: 2.1

orbs:
    win: circleci/windows@2.4.0

jobs:
    build:
        executor: win/default
        environment:
          BUILD_VERSION: << pipeline.parameters.build-version >>
          PIPELINE_NUM: << pipeline.number >>
          PACKAGE: "package"
        steps:
            - run:
                name: build environment variable for package name
                command: |
                    $PARENT_BRANCH = "<< pipeline.git.branch >>".Substring(("<< pipeline.git.branch >>".IndexOf('/'))+1)
                    [System.Environment]::SetEnvironmentVariable('DOCKER_HOST', 'docker.artofshell.com')
                    echo $DOCKER_HOST
