version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.8
    steps:
      - run: |
          output=$(exit 8; echo 'test')

workflows:
  workflow-should-only-trigger-with-api:
    jobs:
      - build
