version: 2.1

parameters:
  test:
    type: string
    default: 'hi'
jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - checkout
      - run: echo << pipeline.number >>
  other-job:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - checkout
      - run: echo "scheduled workflow"

workflows:
  build:
    jobs:
      - build
  scheduled:
    jobs:
      - other-job
    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              only:
                - master
