version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  slack: circleci/slack@3.4.2

parameters:
  file_id:
    type: string
    default: 'error'

jobs:
  build:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run: python --version
      - run: pip install -r requirements.txt
      - run:
          command: python pa.py << pipeline.parameters.file_id >>
          no_output_timeout: 2h

workflows:
  run-pa:
    jobs:
      - build
      - slack/notify-on-failure

