version: 2.1 # Use version 2.1 to enable orb usage.

parameters:
  file_id:
    type: string
    default: ''

jobs:
  build:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run: python --version
      - run: pip install -r requirements.txt
      - run: python pa.py << pipeline.parameters.file_id >> 
